import type { ExportSession } from "./types";

export function buildMarkdownExport(session: ExportSession): string {
  const meta = [
    `> Generated by Deep Research Platform`,
    `> Session ID: ${session.id}`,
    `> Status: ${session.status}`,
    `> Citation Style: ${session.citationStyle}`,
    `> Created: ${session.createdAt.toISOString()}`,
    `> Updated: ${session.updatedAt.toISOString()}`,
  ].join("\n");

  const payload = [
    `# ${session.topic}`,
    "",
    meta,
    "",
    "## Metadata",
    "```json",
    JSON.stringify({ plan: session.plan, verifiedCitations: session.verifiedCitations }, null, 2),
    "```",
    "",
    "## Report",
    session.finalReport ?? "No synthesized report available.",
  ];

  return payload.join("\n");
}
