"use client";
import { useRef, useState } from "react";
import { ActionCard } from "../cards/ActionCard";
import { ActiveSourcesCard } from "../cards/ActiveSourcesCard";
import { ApiConfigCard } from "../cards/ApiConfigCard";
import { ErrorBox } from "../cards/ErrorBox";
import { OutputCard } from "../cards/OutputCard";
import { ReferenceResultsCard } from "../cards/ReferenceResultsCard";
import { SearchConfigCard } from "../cards/SearchConfigCard";
import { ConsoleLog } from "../console/ConsoleLog";
import type { ApiConfig, CandidateSource, ResearchLogEntry, SearchConfig } from "@/types/research";

export function ResearchConsole(){const year=new Date().getFullYear(); const [searchConfig,setSearchConfig]=useState<SearchConfig>({topic:"",citationStyle:"apa",startYear:2000,endYear:year,searchDepth:50,includePreprints:true,excludePatents:true,onlyOpenAccess:false}); const [apiConfig,setApiConfig]=useState<ApiConfig>({nickname:"",baseUrl:"https://api.deepseek.com",modelId:"deepseek-chat",apiKey:""}); const [logs,setLogs]=useState<ResearchLogEntry[]>([]); const [sources]=useState<CandidateSource[]>([]); const [output,setOutput]=useState(""); const [isRunning,setIsRunning]=useState(false); const [error,setError]=useState(""); const controllerRef=useRef<AbortController|null>(null);
const log=(phase:ResearchLogEntry["phase"],message:string)=>setLogs((p)=>[...p,{id:crypto.randomUUID(),timestamp:new Date().toLocaleTimeString(),phase,message}]);
const handleRun=async()=>{ if(!searchConfig.topic.trim()){setError("Topic is required."); return;} setError(""); setOutput(""); setIsRunning(true); const userId=localStorage.getItem("ds_user_id"); if(!userId){setError("User not initialized."); setIsRunning(false); return;} try{ log("init","Creating research session..."); const createRes=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,topic:searchConfig.topic,citationStyle:searchConfig.citationStyle,depthLevel:searchConfig.searchDepth>70?'deep':'standard',dateRangeStart:searchConfig.startYear,dateRangeEnd:searchConfig.endYear,sourceCount:Math.max(10,Math.round(searchConfig.searchDepth/5))})}); const created=await createRes.json(); if(!createRes.ok) throw new Error(created.error||'Failed to create session'); const sessionId=created.sessionId as string; log("search","Generating research plan..."); controllerRef.current=new AbortController(); const planRes=await fetch(`/api/research/${sessionId}/plan`,{method:'POST',signal:controllerRef.current.signal}); if(!planRes.body) throw new Error("No response stream"); const reader=planRes.body.getReader(); const decoder=new TextDecoder(); let buffer=""; while(true){ const {value,done}=await reader.read(); if(done) break; buffer += decoder.decode(value,{stream:true}); const events = buffer.split("\n\n"); buffer = events.pop() || ""; for(const event of events){ if(!event.startsWith("data: ")) continue; const payload=JSON.parse(event.slice(6)); if(payload.chunk) setOutput((o)=>o+payload.chunk); if(payload.done) { setOutput(JSON.stringify(payload.plan,null,2)); log("synthesis",`Plan complete: ${payload.plan.searchQueries?.length||0} queries`); } if(payload.error) throw new Error(payload.error); } } } catch(e){ if((e as Error).name==="AbortError") log("error","Run aborted."); else {setError((e as Error).message); log("error",`Error: ${(e as Error).message}`);} } finally{setIsRunning(false);} };
const handleExport=(f:"txt"|"bibtex"|"ris")=>console.log("Export",f); const handleStop=()=>{ controllerRef.current?.abort(); setIsRunning(false); };
return <div className="grid gap-6 lg:grid-cols-2"><div className="space-y-4"><SearchConfigCard config={searchConfig} onChange={setSearchConfig}/><ApiConfigCard config={apiConfig} onChange={setApiConfig}/><ActionCard onRun={handleRun} onStop={handleStop} onExport={handleExport} estimatedPapers={Math.max(25,searchConfig.searchDepth*2)} isRunning={isRunning} disableRun={!searchConfig.topic.trim()} /><ActiveSourcesCard sources={sources}/></div><div className="space-y-4">{error&&<ErrorBox message={error}/>}<ConsoleLog entries={logs}/><OutputCard output={output} isLoading={isRunning}/><ReferenceResultsCard sources={sources}/></div></div>;}
