"use client";
import { useRef, useState } from "react";
import { ActionCard } from "../cards/ActionCard";
import { ActiveSourcesCard } from "../cards/ActiveSourcesCard";
import { ApiConfigCard } from "../cards/ApiConfigCard";
import { ErrorBox } from "../cards/ErrorBox";
import { OutputCard } from "../cards/OutputCard";
import { ReferenceResultsCard } from "../cards/ReferenceResultsCard";
import { CitationPanel } from "./CitationPanel";
import { ReportViewer } from "./ReportViewer";
import { SearchConfigCard } from "../cards/SearchConfigCard";
import { ConsoleLog } from "../console/ConsoleLog";
import type { ApiConfig, CandidateSource, ResearchLogEntry, SearchConfig } from "@/types/research";
import type { VerifiedCitation } from "@/lib/ranking/types";

export function ResearchConsole(){const year=new Date().getFullYear();const [searchConfig,setSearchConfig]=useState<SearchConfig>({topic:"",citationStyle:"apa",startYear:2000,endYear:year,searchDepth:50,includePreprints:true,excludePatents:true,onlyOpenAccess:false});const [apiConfig,setApiConfig]=useState<ApiConfig>({nickname:"",baseUrl:"https://api.deepseek.com",modelId:"deepseek-chat",apiKey:""});const [logs,setLogs]=useState<ResearchLogEntry[]>([]);const [sources,setSources]=useState<CandidateSource[]>([]);const [counts,setCounts]=useState({total:0,journal:0,preprint:0,web:0});const [output,setOutput]=useState("");const [isRunning,setIsRunning]=useState(false);const [error,setError]=useState("");const [report,setReport]=useState("");const [citations,setCitations]=useState<VerifiedCitation[]>([]);const controllerRef=useRef<AbortController|null>(null);const log=(phase:ResearchLogEntry["phase"],message:string)=>setLogs(p=>[...p,{id:crypto.randomUUID(),timestamp:new Date().toLocaleTimeString(),phase,message}]);
const streamSse=async(url:string,onData:(payload:any)=>Promise<void>|void)=>{const res=await fetch(url,{method:"POST",signal:controllerRef.current?.signal});if(!res.body) throw new Error("No response stream");const r=res.body.getReader();const d=new TextDecoder();let b="";while(true){const {value,done}=await r.read();if(done) break;b+=d.decode(value,{stream:true});const events=b.split("\n\n");b=events.pop()||"";for(const e of events){if(!e.startsWith("data: ")) continue;await onData(JSON.parse(e.slice(6)));}}};
const handleRun=async()=>{if(!searchConfig.topic.trim()) return;setError("");setOutput("");setReport("");setCitations([]);setSources([]);setCounts({total:0,journal:0,preprint:0,web:0});setIsRunning(true);controllerRef.current=new AbortController();try{const userId=localStorage.getItem("ds_user_id");if(!userId) throw new Error("User not initialized.");const createRes=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,topic:searchConfig.topic,citationStyle:searchConfig.citationStyle,depthLevel:searchConfig.searchDepth>70?'deep':'standard',dateRangeStart:searchConfig.startYear,dateRangeEnd:searchConfig.endYear,sourceCount:Math.max(10,Math.round(searchConfig.searchDepth/5))})});const created=await createRes.json();if(!createRes.ok) throw new Error(created.error);const sid=created.sessionId as string;
log("search","Generating research plan...");await streamSse(`/api/research/${sid}/plan`,(p)=>{if(p.chunk) setOutput(o=>o+p.chunk); if(p.done) log("search","Plan complete"); if(p.error) throw new Error(p.error);});
log("search","Starting source retrieval...");await streamSse(`/api/research/${sid}/search`,(p)=>{if(p.type==="log") log("search",p.message); if(p.type==="source"){setSources(prev=>[...prev,p.source]);setCounts(p.counts);} if(p.type==="done") log("search",`Search complete: ${p.total}`); if(p.type==="error") throw new Error(p.error);});
log("synthesis","Auto-ranking sources...");await streamSse(`/api/research/${sid}/rank`,(p)=>{if(p.type==="scored") log("synthesis",`#${p.index}/${p.total} [${p.score}] ${p.source}`); if(p.type==="done"){setSources(p.ranked);log("synthesis","Ranking complete");} if(p.type==="error") throw new Error(p.error);});
log("synthesis","Verifying citations...");await streamSse(`/api/research/${sid}/verify`,(p)=>{if(p.type==="verified"){ setCitations(prev=>[...prev,p.item]); log("synthesis",`Checking ${p.index}/${p.total}: ${p.item.title}`);} if(p.type==="done") log("synthesis","Verification complete; status -> synthesizing"); if(p.type==="error") throw new Error(p.error);});
log("synthesis","Generating research report...");await streamSse(`/api/research/${sid}/synthesize`,(p)=>{if(p.type==="token") setReport(r=>r+p.token); if(p.type==="done") log("synthesis",`Report complete: ${p.length} characters`); if(p.type==="error") throw new Error(p.error);});

}catch(e){if((e as Error).name!=="AbortError"){setError((e as Error).message);log("error",(e as Error).message);}else log("error","Run aborted.");}finally{setIsRunning(false);}};
return <div className="grid gap-6 lg:grid-cols-2"><div className="space-y-4"><SearchConfigCard config={searchConfig} onChange={setSearchConfig}/><ApiConfigCard config={apiConfig} onChange={setApiConfig}/><ActionCard onRun={handleRun} onStop={()=>controllerRef.current?.abort()} onExport={()=>{}} estimatedPapers={Math.max(25,searchConfig.searchDepth*2)} isRunning={isRunning} disableRun={!searchConfig.topic.trim()}/><ActiveSourcesCard counts={counts}/></div><div className="space-y-4">{error&&<ErrorBox message={error}/>}<ConsoleLog entries={logs}/><OutputCard output={output} isLoading={isRunning}/><ReportViewer report={report} isStreaming={isRunning}/><CitationPanel citations={citations} citationStyle={searchConfig.citationStyle as "apa"|"mla"}/><ReferenceResultsCard sources={sources}/></div></div>;}
